# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ikttBZHzgIvioBfXlCOIa6fjDluVCuFS
            client-secret: 2nDloO_NsQOL5CIRgEf4VfPMoURDz3a3WRjnVKGkD7UrkJFdur03XP0QXalwXNI1
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-bebggfy2.us.auth0.com/