# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: EjDHw80iE9ypQYbG1ELs91p3qHabJYo5
            client-secret: zw9MTuLdeghHR_xrxrfG9XAQGDOAtqsIpDdc3CkSYqZTqPcDoZbsEEF8UX0b4XQd
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-wcfa2rp4.us.auth0.com/