# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: gblcYaI4Xc3CzquLNJVpYfXMO8RX3Aee
            client-secret: suLD9J_PoIRJGBbl82ku_vWNaiG7v034uo3CRhyI4ItXfNEYuKPSXiQIz716_gPz
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://throbbing-brook-9357.us.auth0.com/